### ISSUE TITLE
Error: Unable to read the license file

### ISSUE THREAD

**Issue by codyfazio** [quire-io/SwiftyChrono#1]
I'm having an issue adding the pod to my project. I get the error "Unable to read the license file". Any suggestions?

**Comment by jerrywell** [comment]
my pods version is 1.2.0. it works good. according to https://github.com/CocoaPods/CocoaPods/issues/5711, you may need to update your cocoapods to the latest version.

**Comment by jerrywell** [comment]
can you provide the version of cocopods? my pods version is 1.2.0, it works good.

**Comment by codyfazio** [comment]
Apparently that was the problem! I updated to 1.2.0 and it added with no problems. Thanks for the help!

**Comment by jerrywell** [comment]
License file in podspec has wrong name
