### ISSUE TITLE
Build Errors swift 4

### ISSUE THREAD

**Issue by chrishorton** [quire-io/SwiftyChrono#5]
Install with Cocoapods, get these errors

<img width="1440" alt="screen shot 2018-01-11 at 10 57 06 pm" src="https://user-images.githubusercontent.com/12613672/34863153-c565e316-f722-11e7-91f0-07e836947716.png">

**Comment by chrishorton** [comment]
Ok so I fixed the first one just by making ModeOption public (per Xcode's Suggestion) but the second one is still stumping me

**Comment by windtalkerlv** [comment]
A stab in the dark but did you try to change the pod Build Settings of Swift Language Version to swift 3.2? I didnt change anything else and It did the trick for me

**Comment by jerrywell** [comment]
we've upgraded to Swift 4.2 so i will close this issue. thanks.
